// Bijoux Oriabel — Artikel-Daten
// Felder: id, titel, kategorie (kette|ohrring|armband), beschreibung, bild, material, groesse, jahr, verfuegbarkeit

const SCHMUCK_DATEN = [
  {  id:"marguerite-kette",   titel:"Marguerite â Collier",   kategorie:"kette",   beschreibung:"Fine chaÃ®ne dorÃ©e avec pendentif fleur en nacre blanche. Sobre et Ã©lÃ©gant.",   bild:"uploads/2019/02/P1070661.jpg",   material:"Laiton doré, nacre",   groesse:"Longueur 42 cm",   jahr:"2019",   verfuegbarkeit:"Sur demande"},
  {  id:"cauri-monstera",   titel:"Cauri & Monstera",   kategorie:"kette",   beschreibung:"Coquillage cauri avec charm feuille de monstera sur chaÃ®ne dorÃ©e. Tropical, naturel.",   bild:"uploads/2019/02/P1070691.jpg",   material:"Laiton dorÃ©, coquillage cauri",   groesse:"Longueur 45 cm",   jahr:"2019",   verfuegbarkeit:"Sur demande"},
  {  id:"chat-katzchen",   titel:"Chat â Chaton",   kategorie:"kette",   beschreibung:"Collier en perles Miyuki colorÃ©es avec charm chaton dorÃ©. Fantaisie et unique.",   bild:"uploads/2019/02/P1070699.jpg",   material:"Perles Miyuki, laiton dorÃ©",   groesse:"Longueur 40 cm",   jahr:"2019",   verfuegbarkeit:"Sur demande"},
  {  id:"coeur-dore",   titel:"CÅur DorÃ©",   kategorie:"kette",   beschreibung:"CÅur en laiton dorÃ© finement travaillÃ© sur chaÃ®ne bronze. Romantique et intemporel.",   bild:"uploads/2019/02/P1070728.jpg",   material:"Laiton dorÃ©, chaÃ®ne bronze",   groesse:"Longueur 50 cm",   jahr:"2019",   verfuegbarkeit:"Sur demande"},
  {  id:"cristal-y-kette",   titel:"Cristal â Collier Y",   kategorie:"kette",   beschreibung:"Collier Y avec maillons en cristal de roche et perles. Lumineux, Ã©lÃ©gant.",   bild:"uploads/2019/02/P1070733.jpg",   material:"Laiton dorÃ©, cristal de roche",   groesse:"Longueur 55 cm",   jahr:"2019",   verfuegbarkeit:"Sur demande"},
  {  id:"oups-wire-art",   titel:"OUPS â Wire Art",   kategorie:"kette",   beschreibung:"Collier Wire Art avec le mot OUPS en fil dorÃ©. Ironique, portable, unique.",   bild:"uploads/2019/02/P1070949.jpg",   material:"Fil dorÃ©, chaÃ®ne dorÃ©e",   groesse:"Longueur 42 cm",   jahr:"2019",   verfuegbarkeit:"Sur demande"},
  {  id:"dalmatien-quaste",   titel:"Dalmatien & Pompon",   kategorie:"kette",   beschreibung:"Longue chaÃ®ne bronze avec perles jaspe dalmatien et pompon orange. Style bohÃ¨me.",   bild:"uploads/2019/02/P1070716.jpg",   material:"ChaÃ®ne bronze, jaspe dalmatien",   groesse:"Longueur 80 cm",   jahr:"2019",   verfuegbarkeit:"Sur demande"},
  {  id:"marguerite-cascade",   titel:"Marguerite Cascade",   kategorie:"ohrring",   beschreibung:"Boucles pendantes avec fleur en nacre et cascades de perles blanches. Festives et lÃ©gÃ¨res.",   bild:"uploads/2019/02/P1070662.jpg",   material:"Laiton dorÃ©, nacre, perles verre",   groesse:"Longueur 5 cm",   jahr:"2019",   verfuegbarkeit:"Sur demande"},
  {  id:"marguerite-bar",   titel:"Marguerite Bar",   kategorie:"ohrring",   beschreibung:"Boucles Ã©lÃ©gantes: longue barre dorÃ©e avec fleur en nacre. GÃ©omÃ©trique et fÃ©minin.",   bild:"uploads/2019/02/P1070663.jpg",   material:"Laiton dorÃ©, nacre",   groesse:"Longueur 6 cm",   jahr:"2019",   verfuegbarkeit:"Sur demande"},
  {  id:"pierre-noire",   titel:"Pierre Noire",   kategorie:"ohrring",   beschreibung:"Longue chaÃ®ne dorÃ©e avec grandes perles en pierre noire. Fort et moderne.",   bild:"uploads/2019/02/P1070672.jpg",   material:"Laiton dorÃ©, pierre minÃ©rale",   groesse:"Longueur 8 cm",   jahr:"2019",   verfuegbarkeit:"Sur demande"},
  {  id:"atelier-set",   titel:"Atelier â Trio",   kategorie:"ohrring",   beschreibung:"Trois paires de boucles pendantes sur prÃ©sentoir bois â Art dÃ©co, pierre naturelle, cristal.",   bild:"uploads/2019/02/P1070913.jpg",   material:"Laiton dorÃ©, pierres naturelles",   groesse:"Longueur 5â8 cm",   jahr:"2019",   verfuegbarkeit:"Sur demande"},
  {  id:"ambre-bernstein",   titel:"Ambre Baltique",   kategorie:"ohrring",   beschreibung:"Trois paires de boucles en ambre baltique â du cognac sombre au miel chaud.",   bild:"uploads/2019/02/P1070936.jpg",   material:"Ambre baltique, laiton dorÃ©",   groesse:"Longueur 6â8 cm",   jahr:"2019",   verfuegbarkeit:"Sur demande"},
  {  id:"grenat-granat",   titel:"Grenat",   kategorie:"ohrring",   beschreibung:"Boucles pendantes avec perles grenat rouge profond sur fine chaÃ®ne dorÃ©e. Noble et intemporel.",   bild:"uploads/2019/02/P1070934.jpg",   material:"Grenat, laiton dorÃ©",   groesse:"Longueur 7 cm",   jahr:"2019",   verfuegbarkeit:"Sur demande"},
  {  id:"creole",   titel:"CrÃ©ole",   kategorie:"ohrring",   beschreibung:"Grandes crÃ©oles avec perles Miyuki. LÃ©gÃ¨res comme l'Ã©tÃ©.",   bild:"uploads/2019/02/P1080029.jpg",   material:"Laiton dorÃ©, perles Miyuki",   groesse:"DiamÃ¨tre 5 cm",   jahr:"2019",   verfuegbarkeit:"Sur demande"},
  {  id:"opale-set",   titel:"Opale â Ensemble 4",   kategorie:"armband",   beschreibung:"Quatre bracelets dÃ©licats avec perles opale bleu clair et fermoir dorÃ©. Portables ensemble ou sÃ©parÃ©ment.",   bild:"uploads/2019/02/P1070675.jpg",   material:"Perles opale, laiton dorÃ©",   groesse:"Longueur 18 cm",   jahr:"2019",   verfuegbarkeit:"Sur demande"},
  {  id:"opale-display",   titel:"Opale â Display",   kategorie:"armband",   beschreibung:"Bracelets opale prÃ©sentÃ©s sur prÃ©sentoir sombre â ambiance maritime.",   bild:"uploads/2019/02/P1070683.jpg",   material:"Perles opale, laiton dorÃ©",   groesse:"Longueur 18 cm",   jahr:"2019",   verfuegbarkeit:"Sur demande"},
  {  id:"terre-cuite",   titel:"Terre Cuite â Ensemble",   kategorie:"armband",   beschreibung:"Bracelet et boucles en perles de verre terracotta avec fermoir T-bar dorÃ©.",   bild:"uploads/2019/02/P1070685.jpg",   material:"Perles verre, laiton dorÃ©",   groesse:"Bracelet 18 cm",   jahr:"2019",   verfuegbarkeit:"Sur demande"}
];
