// Bijoux Oriabel — Artikel-Daten
// Felder: id, titel, kategorie (kette|ohrring|armband), beschreibung, bild, material, groesse, jahr, verfuegbarkeit

const SCHMUCK_DATEN = [
  {  id:"marguerite-kette",   titel:"Marguerite Ã¢ÂÂ Collier",   kategorie:"kette",   beschreibung:"Fine chaÃÂ®ne dorÃÂ©e avec pendentif fleur en nacre blanche. Sobre et ÃÂ©lÃÂ©gant.",   bild:"uploads/2019/02/P1070661.jpg",   material:"Laiton dorÃ©, nacre",   groesse:"Longueur 42 cm",   jahr:"2019",   verfuegbarkeit:"Sur demande"},
  {  id:"cauri-monstera",   titel:"Cauri & Monstera",   kategorie:"kette",   beschreibung:"Coquillage cauri avec charm feuille de monstera sur chaÃÂ®ne dorÃÂ©e. Tropical, naturel.",   bild:"uploads/2019/02/P1070691.jpg",   material:"Laiton dorÃÂ©, coquillage cauri",   groesse:"Longueur 45 cm",   jahr:"2019",   verfuegbarkeit:"Sur demande"},
  {  id:"chat-katzchen",   titel:"Chat Ã¢ÂÂ Chaton",   kategorie:"kette",   beschreibung:"Collier en perles Miyuki colorÃÂ©es avec charm chaton dorÃÂ©. Fantaisie et unique.",   bild:"uploads/2019/02/P1070699.jpg",   material:"Perles Miyuki, laiton dorÃÂ©",   groesse:"Longueur 40 cm",   jahr:"2019",   verfuegbarkeit:"Sur demande"},
  {  id:"coeur-dore",   titel:"CÃÂur DorÃÂ©",   kategorie:"kette",   beschreibung:"CÃÂur en laiton dorÃÂ© finement travaillÃÂ© sur chaÃÂ®ne bronze. Romantique et intemporel.",   bild:"uploads/2019/02/P1070728.jpg",   material:"Laiton dorÃÂ©, chaÃÂ®ne bronze",   groesse:"Longueur 50 cm",   jahr:"2019",   verfuegbarkeit:"Sur demande"},
  {  id:"cristal-y-kette",   titel:"Cristal Ã¢ÂÂ Collier Y",   kategorie:"kette",   beschreibung:"Collier Y avec maillons en cristal de roche et perles. Lumineux, ÃÂ©lÃÂ©gant.",   bild:"uploads/2019/02/P1070733.jpg",   material:"Laiton dorÃÂ©, cristal de roche",   groesse:"Longueur 55 cm",   jahr:"2019",   verfuegbarkeit:"Sur demande"},
  {  id:"oups-wire-art",   titel:"OUPS Ã¢ÂÂ Wire Art",   kategorie:"kette",   beschreibung:"Collier Wire Art avec le mot OUPS en fil dorÃÂ©. Ironique, portable, unique.",   bild:"uploads/2019/02/P1070949.jpg",   material:"Fil dorÃÂ©, chaÃÂ®ne dorÃÂ©e",   groesse:"Longueur 42 cm",   jahr:"2019",   verfuegbarkeit:"Sur demande"},
  {  id:"dalmatien-quaste",   titel:"Dalmatien & Pompon",   kategorie:"kette",   beschreibung:"Longue chaÃÂ®ne bronze avec perles jaspe dalmatien et pompon orange. Style bohÃÂ¨me.",   bild:"uploads/2019/02/P1070716.jpg",   material:"ChaÃÂ®ne bronze, jaspe dalmatien",   groesse:"Longueur 80 cm",   jahr:"2019",   verfuegbarkeit:"Sur demande"},
  {  id:"marguerite-cascade",   titel:"Marguerite Cascade",   kategorie:"ohrring",   beschreibung:"Boucles pendantes avec fleur en nacre et cascades de perles blanches. Festives et lÃÂ©gÃÂ¨res.",   bild:"uploads/2019/02/P1070662.jpg",   material:"Laiton dorÃÂ©, nacre, perles verre",   groesse:"Longueur 5 cm",   jahr:"2019",   verfuegbarkeit:"Sur demande"},
  {  id:"marguerite-bar",   titel:"Marguerite Bar",   kategorie:"ohrring",   beschreibung:"Boucles ÃÂ©lÃÂ©gantes: longue barre dorÃÂ©e avec fleur en nacre. GÃÂ©omÃÂ©trique et fÃÂ©minin.",   bild:"uploads/2019/02/P1070663.jpg",   material:"Laiton dorÃÂ©, nacre",   groesse:"Longueur 6 cm",   jahr:"2019",   verfuegbarkeit:"Sur demande"},
  {  id:"pierre-noire",   titel:"Pierre Noire",   kategorie:"ohrring",   beschreibung:"Longue chaÃÂ®ne dorÃÂ©e avec grandes perles en pierre noire. Fort et moderne.",   bild:"uploads/2019/02/P1070672.jpg",   material:"Laiton dorÃÂ©, pierre minÃÂ©rale",   groesse:"Longueur 8 cm",   jahr:"2019",   verfuegbarkeit:"Sur demande"},
  {  id:"atelier-set",   titel:"Atelier Ã¢ÂÂ Trio",   kategorie:"ohrring",   beschreibung:"Trois paires de boucles pendantes sur prÃÂ©sentoir bois Ã¢ÂÂ Art dÃÂ©co, pierre naturelle, cristal.",   bild:"uploads/2019/02/P1070913.jpg",   material:"Laiton dorÃÂ©, pierres naturelles",   groesse:"Longueur 5Ã¢ÂÂ8 cm",   jahr:"2019",   verfuegbarkeit:"Sur demande"},
  {  id:"ambre-bernstein",   titel:"Ambre Baltique",   kategorie:"ohrring",   beschreibung:"Trois paires de boucles en ambre baltique Ã¢ÂÂ du cognac sombre au miel chaud.",   bild:"uploads/2019/02/P1070936.jpg",   material:"Ambre baltique, laiton dorÃÂ©",   groesse:"Longueur 6Ã¢ÂÂ8 cm",   jahr:"2019",   verfuegbarkeit:"Sur demande"},
  {  id:"grenat-granat",   titel:"Grenat",   kategorie:"ohrring",   beschreibung:"Boucles pendantes avec perles grenat rouge profond sur fine chaÃÂ®ne dorÃÂ©e. Noble et intemporel.",   bild:"uploads/2019/02/P1070934.jpg",   material:"Grenat, laiton dorÃÂ©",   groesse:"Longueur 7 cm",   jahr:"2019",   verfuegbarkeit:"Sur demande"},
  {  id:"creole",   titel:"CrÃÂ©ole",   kategorie:"ohrring",   beschreibung:"Grandes crÃÂ©oles avec perles Miyuki. LÃÂ©gÃÂ¨res comme l'ÃÂ©tÃÂ©.",   bild:"uploads/2019/02/P1080029.jpg",   material:"Laiton dorÃÂ©, perles Miyuki",   groesse:"DiamÃÂ¨tre 5 cm",   jahr:"2019",   verfuegbarkeit:"Sur demande"},
  {  id:"opale-set",   titel:"Opale Ã¢ÂÂ Ensemble 4",   kategorie:"armband",   beschreibung:"Quatre bracelets dÃÂ©licats avec perles opale bleu clair et fermoir dorÃÂ©. Portables ensemble ou sÃÂ©parÃÂ©ment.",   bild:"uploads/2019/02/P1070675.jpg",   material:"Perles opale, laiton dorÃÂ©",   groesse:"Longueur 18 cm",   jahr:"2019",   verfuegbarkeit:"Sur demande"},
  {  id:"opale-display",   titel:"Opale Ã¢ÂÂ Display",   kategorie:"armband",   beschreibung:"Bracelets opale prÃÂ©sentÃÂ©s sur prÃÂ©sentoir sombre Ã¢ÂÂ ambiance maritime.",   bild:"uploads/2019/02/P1070683.jpg",   material:"Perles opale, laiton dorÃÂ©",   groesse:"Longueur 18 cm",   jahr:"2019",   verfuegbarkeit:"Sur demande"},
  {  id:"terre-cuite",   titel:"Terre Cuite Ã¢ÂÂ Ensemble",   kategorie:"armband",   beschreibung:"Bracelet et boucles en perles de verre terracotta avec fermoir T-bar dorÃÂ©.",   bild:"uploads/2019/02/P1070685.jpg",   material:"Perles verre, laiton dorÃÂ©",   groesse:"Bracelet 18 cm",   jahr:"2019",   verfuegbarkeit:"Sur demande"}
];
