/* Oriabel — Bereiche (automatisch generiert, Verwaltung über Admin-Panel) */
window.BEREICHE_DATEN = [
    {
        "id": "edigne",
        "section": "edigne",
        "titre": "Peintures — Edigne Parisis",
        "sous_titre": "Chaque œuvre raconte la lumière, l'espace et l'émotion.",
        "titre_nav": "Edigne Parisis",
        "kuenstlerin": "Edigne Parisis",
        "bildform": "portrait",
        "feld1_key": "technik",
        "feld1_label": "Technique",
        "feld2_key": "format",
        "feld2_label": "Format",
        "feld3_key": "jahr",
        "feld3_label": "Année",
        "kategorien": [
            {
                "id": "figuratif",
                "label": "Figuratif"
            },
            {
                "id": "paysage",
                "label": "Paysage & Ville"
            },
            {
                "id": "abstrait",
                "label": "Abstrait"
            },
            {
                "id": "autres",
                "label": "Autres œuvres"
            }
        ],
        "produkte": [
            {
                "id": "tableau-003",
                "titel": "Tableau 003",
                "kategorie": "figuratif",
                "beschreibung": "Huile sur toile. Une composition colorée, pleine d'énergie et de profondeur.",
                "bild": "uploads/2019/02/Tableau-003.jpg",
                "vorschau": "uploads/2019/02/Tableau-003.jpg",
                "technik": "Huile sur toile",
                "format": "60 × 80 cm",
                "jahr": "2019",
                "verfuegbarkeit": "Sur demande"
            },
            {
                "id": "tableau-005",
                "titel": "Tableau 005",
                "kategorie": "figuratif",
                "beschreibung": "La lumière et l'ombre en dialogue — portrait expressif et atmosphérique.",
                "bild": "uploads/2019/02/Tableau-005.jpg",
                "vorschau": "uploads/2019/02/Tableau-005.jpg",
                "technik": "Huile sur toile",
                "format": "50 × 70 cm",
                "jahr": "2019",
                "verfuegbarkeit": "Sur demande"
            },
            {
                "id": "tableau-007",
                "titel": "Tableau 007",
                "kategorie": "figuratif",
                "beschreibung": "Grande toile à la palette audacieuse et au coup de pinceau souverain.",
                "bild": "uploads/2019/02/Tableau-007.jpg",
                "vorschau": "uploads/2019/02/Tableau-007.jpg",
                "technik": "Huile sur toile",
                "format": "80 × 100 cm",
                "jahr": "2019",
                "verfuegbarkeit": "Sur demande"
            },
            {
                "id": "11-novembre",
                "titel": "11 Novembre — Ville Donner",
                "kategorie": "paysage",
                "beschreibung": "Style naïf, scène populaire finement détaillée. Le 11 Novembre, fête du souvenir.",
                "bild": "uploads/2019/02/DSC02328.jpg",
                "vorschau": "uploads/2019/02/DSC02328.jpg",
                "technik": "Huile sur toile",
                "format": "70 × 90 cm",
                "jahr": "2018",
                "verfuegbarkeit": "Sur demande"
            },
            {
                "id": "rue-de-ville",
                "titel": "Rue de Ville",
                "kategorie": "paysage",
                "beschreibung": "Scène urbaine impressionniste avec clocher, signée E. Parisis.",
                "bild": "uploads/2019/02/IMG_7011.jpg",
                "vorschau": "uploads/2019/02/IMG_7011.jpg",
                "technik": "Huile sur toile",
                "format": "60 × 80 cm",
                "jahr": "vers 1950",
                "verfuegbarkeit": "Sur demande"
            },
            {
                "id": "plage-de-nice",
                "titel": "Plage de Nice",
                "kategorie": "paysage",
                "beschreibung": "La baie de Nice dans la lumière de midi. Grand format, atmosphère méditerranéenne.",
                "bild": "uploads/2019/02/plage-de-Nice.jpg",
                "vorschau": "uploads/2019/02/plage-de-Nice.jpg",
                "technik": "Huile sur toile",
                "format": "90 × 70 cm",
                "jahr": "2017",
                "verfuegbarkeit": "Sur demande"
            },
            {
                "id": "tableau-021",
                "titel": "Tableau 021",
                "kategorie": "abstrait",
                "beschreibung": "Composition libre — le geste comme expression du mouvement et de la dynamique.",
                "bild": "uploads/2019/02/Tableau-021.jpg",
                "vorschau": "uploads/2019/02/Tableau-021.jpg",
                "technik": "Huile sur toile",
                "format": "70 × 100 cm",
                "jahr": "2018",
                "verfuegbarkeit": "Sur demande"
            },
            {
                "id": "tableau-022",
                "titel": "Tableau 022",
                "kategorie": "abstrait",
                "beschreibung": "Portrait vertical atmosphérique à la palette très expressive.",
                "bild": "uploads/2019/02/Tableau-022.jpg",
                "vorschau": "uploads/2019/02/Tableau-022.jpg",
                "technik": "Technique mixte",
                "format": "50 × 80 cm",
                "jahr": "2018",
                "verfuegbarkeit": "Sur demande"
            },
            {
                "id": "tableau-025",
                "titel": "Tableau 025",
                "kategorie": "abstrait",
                "beschreibung": "Composition puissante — la lumière comme thème central.",
                "bild": "uploads/2019/02/Tableau-025.jpg",
                "vorschau": "uploads/2019/02/Tableau-025.jpg",
                "technik": "Huile sur bois",
                "format": "40 × 60 cm",
                "jahr": "2018",
                "verfuegbarkeit": "Sur demande"
            },
            {
                "id": "tableau-026",
                "titel": "Tableau 026",
                "kategorie": "abstrait",
                "beschreibung": "Transitions fluides entre couleur et forme — acrylique sur toile.",
                "bild": "uploads/2019/02/Tableau-026.jpg",
                "vorschau": "uploads/2019/02/Tableau-026.jpg",
                "technik": "Acrylique sur toile",
                "format": "80 × 80 cm",
                "jahr": "2018",
                "verfuegbarkeit": "Sur demande"
            },
            {
                "id": "tableau-004",
                "titel": "Tableau 004",
                "kategorie": "autres",
                "beschreibung": "Œuvre d'Edigne Parisis.",
                "bild": "uploads/2019/02/Tableau-004.jpg",
                "vorschau": "uploads/2019/02/Tableau-004.jpg",
                "technik": "Huile sur toile",
                "format": "",
                "jahr": "2019",
                "verfuegbarkeit": "Sur demande"
            },
            {
                "id": "tableau-006",
                "titel": "Tableau 006",
                "kategorie": "autres",
                "beschreibung": "Œuvre d'Edigne Parisis.",
                "bild": "uploads/2019/02/Tableau-006.jpg",
                "vorschau": "uploads/2019/02/Tableau-006.jpg",
                "technik": "Huile sur toile",
                "format": "",
                "jahr": "2019",
                "verfuegbarkeit": "Sur demande"
            },
            {
                "id": "tableau-010",
                "titel": "Tableau 010",
                "kategorie": "autres",
                "beschreibung": "Œuvre d'Edigne Parisis.",
                "bild": "uploads/2019/02/Tableau-010.jpg",
                "vorschau": "uploads/2019/02/Tableau-010.jpg",
                "technik": "Huile sur toile",
                "format": "",
                "jahr": "2019",
                "verfuegbarkeit": "Sur demande"
            },
            {
                "id": "tableau-023",
                "titel": "Tableau 023",
                "kategorie": "autres",
                "beschreibung": "Œuvre d'Edigne Parisis.",
                "bild": "uploads/2019/02/Tableau-023.jpg",
                "vorschau": "uploads/2019/02/Tableau-023.jpg",
                "technik": "Huile sur toile",
                "format": "",
                "jahr": "2019",
                "verfuegbarkeit": "Sur demande"
            },
            {
                "id": "tableau-027",
                "titel": "Tableau 027",
                "kategorie": "autres",
                "beschreibung": "Œuvre d'Edigne Parisis.",
                "bild": "uploads/2019/02/Tableau-027.jpg",
                "vorschau": "uploads/2019/02/Tableau-027.jpg",
                "technik": "Huile sur toile",
                "format": "",
                "jahr": "2019",
                "verfuegbarkeit": "Sur demande"
            },
            {
                "id": "tableau-035",
                "titel": "Tableau 035",
                "kategorie": "autres",
                "beschreibung": "Œuvre d'Edigne Parisis.",
                "bild": "uploads/2019/02/Tableau-035.jpg",
                "vorschau": "uploads/2019/02/Tableau-035.jpg",
                "technik": "Huile sur toile",
                "format": "",
                "jahr": "2019",
                "verfuegbarkeit": "Sur demande"
            },
            {
                "id": "tableau-040",
                "titel": "Tableau 040",
                "kategorie": "autres",
                "beschreibung": "Œuvre d'Edigne Parisis.",
                "bild": "uploads/2019/02/Tableau-040.jpg",
                "vorschau": "uploads/2019/02/Tableau-040.jpg",
                "technik": "Huile sur toile",
                "format": "",
                "jahr": "2019",
                "verfuegbarkeit": "Sur demande"
            },
            {
                "id": "tableau-041",
                "titel": "Tableau 041",
                "kategorie": "autres",
                "beschreibung": "Œuvre d'Edigne Parisis.",
                "bild": "uploads/2019/02/Tableau-041.jpg",
                "vorschau": "uploads/2019/02/Tableau-041.jpg",
                "technik": "Huile sur toile",
                "format": "",
                "jahr": "2019",
                "verfuegbarkeit": "Sur demande"
            },
            {
                "id": "tableau-043",
                "titel": "Tableau 043",
                "kategorie": "autres",
                "beschreibung": "Œuvre d'Edigne Parisis.",
                "bild": "uploads/2019/02/Tableau-043.jpg",
                "vorschau": "uploads/2019/02/Tableau-043.jpg",
                "technik": "Huile sur toile",
                "format": "",
                "jahr": "2019",
                "verfuegbarkeit": "Sur demande"
            },
            {
                "id": "tableau-044",
                "titel": "Tableau 044",
                "kategorie": "autres",
                "beschreibung": "Œuvre d'Edigne Parisis.",
                "bild": "uploads/2019/02/Tableau-044.jpg",
                "vorschau": "uploads/2019/02/Tableau-044.jpg",
                "technik": "Huile sur toile",
                "format": "",
                "jahr": "2019",
                "verfuegbarkeit": "Sur demande"
            },
            {
                "id": "tableau-045",
                "titel": "Tableau 045",
                "kategorie": "autres",
                "beschreibung": "Œuvre d'Edigne Parisis.",
                "bild": "uploads/2019/02/Tableau-045.jpg",
                "vorschau": "uploads/2019/02/Tableau-045.jpg",
                "technik": "Huile sur toile",
                "format": "",
                "jahr": "2019",
                "verfuegbarkeit": "Sur demande"
            },
            {
                "id": "tableau-046",
                "titel": "Tableau 046",
                "kategorie": "autres",
                "beschreibung": "Œuvre d'Edigne Parisis.",
                "bild": "uploads/2019/02/Tableau-046.jpg",
                "vorschau": "uploads/2019/02/Tableau-046.jpg",
                "technik": "Huile sur toile",
                "format": "",
                "jahr": "2019",
                "verfuegbarkeit": "Sur demande"
            },
            {
                "id": "tableau-047",
                "titel": "Tableau 047",
                "kategorie": "autres",
                "beschreibung": "Œuvre d'Edigne Parisis.",
                "bild": "uploads/2019/02/Tableau-047.jpg",
                "vorschau": "uploads/2019/02/Tableau-047.jpg",
                "technik": "Huile sur toile",
                "format": "",
                "jahr": "2019",
                "verfuegbarkeit": "Sur demande"
            },
            {
                "id": "tableau-048",
                "titel": "Tableau 048",
                "kategorie": "autres",
                "beschreibung": "Œuvre d'Edigne Parisis.",
                "bild": "uploads/2019/02/Tableau-048.jpg",
                "vorschau": "uploads/2019/02/Tableau-048.jpg",
                "technik": "Huile sur toile",
                "format": "",
                "jahr": "2019",
                "verfuegbarkeit": "Sur demande"
            },
            {
                "id": "tableau-049",
                "titel": "Tableau 049",
                "kategorie": "autres",
                "beschreibung": "Œuvre d'Edigne Parisis.",
                "bild": "uploads/2019/02/Tableau-049.jpg",
                "vorschau": "uploads/2019/02/Tableau-049.jpg",
                "technik": "Huile sur toile",
                "format": "",
                "jahr": "2019",
                "verfuegbarkeit": "Sur demande"
            },
            {
                "id": "tableau-051",
                "titel": "Tableau 051",
                "kategorie": "autres",
                "beschreibung": "Œuvre d'Edigne Parisis.",
                "bild": "uploads/2019/02/Tableau-051.jpg",
                "vorschau": "uploads/2019/02/Tableau-051.jpg",
                "technik": "Huile sur toile",
                "format": "",
                "jahr": "2019",
                "verfuegbarkeit": "Sur demande"
            },
            {
                "id": "tableau-052",
                "titel": "Tableau 052",
                "kategorie": "autres",
                "beschreibung": "Œuvre d'Edigne Parisis.",
                "bild": "uploads/2019/02/Tableau-052.jpg",
                "vorschau": "uploads/2019/02/Tableau-052.jpg",
                "technik": "Huile sur toile",
                "format": "",
                "jahr": "2019",
                "verfuegbarkeit": "Sur demande"
            },
            {
                "id": "tableau-054",
                "titel": "Tableau 054",
                "kategorie": "autres",
                "beschreibung": "Œuvre d'Edigne Parisis.",
                "bild": "uploads/2019/02/Tableau-054.jpg",
                "vorschau": "uploads/2019/02/Tableau-054.jpg",
                "technik": "Huile sur toile",
                "format": "",
                "jahr": "2019",
                "verfuegbarkeit": "Sur demande"
            },
            {
                "id": "tableau-055",
                "titel": "Tableau 055",
                "kategorie": "autres",
                "beschreibung": "Œuvre d'Edigne Parisis.",
                "bild": "uploads/2019/02/Tableau-055.jpg",
                "vorschau": "uploads/2019/02/Tableau-055.jpg",
                "technik": "Huile sur toile",
                "format": "",
                "jahr": "2019",
                "verfuegbarkeit": "Sur demande"
            },
            {
                "id": "tableau-058",
                "titel": "Tableau 058",
                "kategorie": "autres",
                "beschreibung": "Œuvre d'Edigne Parisis.",
                "bild": "uploads/2019/02/Tableau-058.jpg",
                "vorschau": "uploads/2019/02/Tableau-058.jpg",
                "technik": "Huile sur toile",
                "format": "",
                "jahr": "2019",
                "verfuegbarkeit": "Sur demande"
            },
            {
                "id": "tableau-059",
                "titel": "Tableau 059",
                "kategorie": "autres",
                "beschreibung": "Œuvre d'Edigne Parisis.",
                "bild": "uploads/2019/02/Tableau-059.jpg",
                "vorschau": "uploads/2019/02/Tableau-059.jpg",
                "technik": "Huile sur toile",
                "format": "",
                "jahr": "2019",
                "verfuegbarkeit": "Sur demande"
            },
            {
                "id": "tableau-060",
                "titel": "Tableau 060",
                "kategorie": "autres",
                "beschreibung": "Œuvre d'Edigne Parisis.",
                "bild": "uploads/2019/02/Tableau-060.jpg",
                "vorschau": "uploads/2019/02/Tableau-060.jpg",
                "technik": "Huile sur toile",
                "format": "",
                "jahr": "2019",
                "verfuegbarkeit": "Sur demande"
            },
            {
                "id": "tableau-062",
                "titel": "Tableau 062",
                "kategorie": "autres",
                "beschreibung": "Œuvre d'Edigne Parisis.",
                "bild": "uploads/2019/02/Tableau-062.jpg",
                "vorschau": "uploads/2019/02/Tableau-062.jpg",
                "technik": "Huile sur toile",
                "format": "",
                "jahr": "2019",
                "verfuegbarkeit": "Sur demande"
            },
            {
                "id": "tableau-064",
                "titel": "Tableau 064",
                "kategorie": "autres",
                "beschreibung": "Œuvre d'Edigne Parisis.",
                "bild": "uploads/2019/02/Tableau-064.jpg",
                "vorschau": "uploads/2019/02/Tableau-064.jpg",
                "technik": "Huile sur toile",
                "format": "",
                "jahr": "2019",
                "verfuegbarkeit": "Sur demande"
            },
            {
                "id": "tableau-065",
                "titel": "Tableau 065",
                "kategorie": "autres",
                "beschreibung": "Œuvre d'Edigne Parisis.",
                "bild": "uploads/2019/02/Tableau-065.jpg",
                "vorschau": "uploads/2019/02/Tableau-065.jpg",
                "technik": "Huile sur toile",
                "format": "",
                "jahr": "2019",
                "verfuegbarkeit": "Sur demande"
            },
            {
                "id": "tableau-066",
                "titel": "Tableau 066",
                "kategorie": "autres",
                "beschreibung": "Œuvre d'Edigne Parisis.",
                "bild": "uploads/2019/02/Tableau-066.jpg",
                "vorschau": "uploads/2019/02/Tableau-066.jpg",
                "technik": "Huile sur toile",
                "format": "",
                "jahr": "2019",
                "verfuegbarkeit": "Sur demande"
            },
            {
                "id": "tableau-067",
                "titel": "Tableau 067",
                "kategorie": "autres",
                "beschreibung": "Œuvre d'Edigne Parisis.",
                "bild": "uploads/2019/02/Tableau-067.jpg",
                "vorschau": "uploads/2019/02/Tableau-067.jpg",
                "technik": "Huile sur toile",
                "format": "",
                "jahr": "2019",
                "verfuegbarkeit": "Sur demande"
            },
            {
                "id": "tableau-068",
                "titel": "Tableau 068",
                "kategorie": "autres",
                "beschreibung": "Œuvre d'Edigne Parisis.",
                "bild": "uploads/2019/02/Tableau-068.jpg",
                "vorschau": "uploads/2019/02/Tableau-068.jpg",
                "technik": "Huile sur toile",
                "format": "",
                "jahr": "2019",
                "verfuegbarkeit": "Sur demande"
            },
            {
                "id": "tableau-072",
                "titel": "Tableau 072",
                "kategorie": "autres",
                "beschreibung": "Œuvre d'Edigne Parisis.",
                "bild": "uploads/2019/02/Tableau-072.jpg",
                "vorschau": "uploads/2019/02/Tableau-072.jpg",
                "technik": "Huile sur toile",
                "format": "",
                "jahr": "2019",
                "verfuegbarkeit": "Sur demande"
            },
            {
                "id": "tableau-075",
                "titel": "Tableau 075",
                "kategorie": "autres",
                "beschreibung": "Œuvre d'Edigne Parisis.",
                "bild": "uploads/2019/02/Tableau-075.jpg",
                "vorschau": "uploads/2019/02/Tableau-075.jpg",
                "technik": "Huile sur toile",
                "format": "",
                "jahr": "2019",
                "verfuegbarkeit": "Sur demande"
            },
            {
                "id": "tableau-076",
                "titel": "Tableau 076",
                "kategorie": "autres",
                "beschreibung": "Œuvre d'Edigne Parisis.",
                "bild": "uploads/2019/02/Tableau-076.jpg",
                "vorschau": "uploads/2019/02/Tableau-076.jpg",
                "technik": "Huile sur toile",
                "format": "",
                "jahr": "2019",
                "verfuegbarkeit": "Sur demande"
            },
            {
                "id": "tableau-077",
                "titel": "Tableau 077",
                "kategorie": "autres",
                "beschreibung": "Œuvre d'Edigne Parisis.",
                "bild": "uploads/2019/02/Tableau-077.jpg",
                "vorschau": "uploads/2019/02/Tableau-077.jpg",
                "technik": "Huile sur toile",
                "format": "",
                "jahr": "2019",
                "verfuegbarkeit": "Sur demande"
            },
            {
                "id": "tableau-078",
                "titel": "Tableau 078",
                "kategorie": "autres",
                "beschreibung": "Œuvre d'Edigne Parisis.",
                "bild": "uploads/2019/02/Tableau-078.jpg",
                "vorschau": "uploads/2019/02/Tableau-078.jpg",
                "technik": "Huile sur toile",
                "format": "",
                "jahr": "2019",
                "verfuegbarkeit": "Sur demande"
            },
            {
                "id": "tableau-079",
                "titel": "Tableau 079",
                "kategorie": "autres",
                "beschreibung": "Œuvre d'Edigne Parisis.",
                "bild": "uploads/2019/02/Tableau-079.jpg",
                "vorschau": "uploads/2019/02/Tableau-079.jpg",
                "technik": "Huile sur toile",
                "format": "",
                "jahr": "2019",
                "verfuegbarkeit": "Sur demande"
            }
        ]
    },
    {
        "id": "bijoux",
        "section": "oriabel",
        "titre": "Bijoux",
        "sous_titre": "Bijoux faits main — pierres naturelles, coquillages et laiton doré. Chaque pièce est unique.",
        "titre_nav": "Bijoux",
        "kuenstlerin": "Oriabel",
        "bildform": "square",
        "feld1_key": "material",
        "feld1_label": "Matière",
        "feld2_key": "groesse",
        "feld2_label": "Taille",
        "feld3_key": "",
        "feld3_label": "",
        "kategorien": [
            {
                "id": "kette",
                "label": "Colliers"
            },
            {
                "id": "ohrring",
                "label": "Boucles d'oreilles"
            },
            {
                "id": "armband",
                "label": "Bracelets"
            },
            {
                "id": "archive",
                "label": "Archives"
            }
        ],
        "produkte": [
            {
                "id": "marguerite-collier",
                "titel": "Marguerite — Collier",
                "kategorie": "kette",
                "beschreibung": "Fin collier doré avec pendentif fleur en nacre blanche. Sobre et élégant.",
                "bild": "uploads/2019/02/P1070661.jpg",
                "vorschau": "uploads/2019/02/P1070661.jpg",
                "material": "Laiton doré, nacre",
                "groesse": "Longueur 42 cm",
                "jahr": "2019",
                "verfuegbarkeit": "Sur demande"
            },
            {
                "id": "cauri-monstera",
                "titel": "Cauri & Monstera",
                "kategorie": "kette",
                "beschreibung": "Coquillage cauri avec breloque feuille de monstera sur chaîne dorée à boules. Tropical, naturel.",
                "bild": "uploads/2019/02/P1070691.jpg",
                "vorschau": "uploads/2019/02/P1070691.jpg",
                "material": "Laiton doré, coquillage cauri",
                "groesse": "Longueur 45 cm",
                "jahr": "2019",
                "verfuegbarkeit": "Sur demande"
            },
            {
                "id": "chat-chaton",
                "titel": "Chat — Chaton",
                "kategorie": "kette",
                "beschreibung": "Collier de perles Miyuki colorées avec breloque chaton doré. Espiègle et unique.",
                "bild": "uploads/2019/02/P1070699.jpg",
                "vorschau": "uploads/2019/02/P1070699.jpg",
                "material": "Perles Miyuki, laiton doré",
                "groesse": "Longueur 40 cm",
                "jahr": "2019",
                "verfuegbarkeit": "Sur demande"
            },
            {
                "id": "coeur-dore",
                "titel": "Cœur Doré",
                "kategorie": "kette",
                "beschreibung": "Cœur finement travaillé en laiton doré sur chaîne bronzée. Romantique et intemporel.",
                "bild": "uploads/2019/02/P1070728.jpg",
                "vorschau": "uploads/2019/02/P1070728.jpg",
                "material": "Laiton doré, chaîne bronze",
                "groesse": "Longueur 50 cm",
                "jahr": "2019",
                "verfuegbarkeit": "Sur demande"
            },
            {
                "id": "cristal-y",
                "titel": "Cristal — Collier en Y",
                "kategorie": "kette",
                "beschreibung": "Collier en Y avec maillons en cristal de roche et perles. Lumineux et élégant.",
                "bild": "uploads/2019/02/P1070733.jpg",
                "vorschau": "uploads/2019/02/P1070733.jpg",
                "material": "Laiton doré, cristal de roche",
                "groesse": "Longueur 55 cm",
                "jahr": "2019",
                "verfuegbarkeit": "Sur demande"
            },
            {
                "id": "oups-wire-art",
                "titel": "OUPS — Wire Art",
                "kategorie": "kette",
                "beschreibung": "Collier wire art avec l'inscription OUPS en fil doré. Ironique, portable, unique.",
                "bild": "uploads/2019/02/P1070949.jpg",
                "vorschau": "uploads/2019/02/P1070949.jpg",
                "material": "Fil doré, chaîne dorée",
                "groesse": "Longueur 42 cm",
                "jahr": "2019",
                "verfuegbarkeit": "Sur demande"
            },
            {
                "id": "dalmatien-pompon",
                "titel": "Dalmatien & Pompon",
                "kategorie": "kette",
                "beschreibung": "Long collier bronze avec perles en jaspe dalmatien et pompon orange. Style bohème.",
                "bild": "uploads/2019/02/P1070716.jpg",
                "vorschau": "uploads/2019/02/P1070716.jpg",
                "material": "Chaîne bronze, jaspe dalmatien",
                "groesse": "Longueur 80 cm",
                "jahr": "2019",
                "verfuegbarkeit": "Sur demande"
            },
            {
                "id": "marguerite-cascade",
                "titel": "Marguerite Cascade",
                "kategorie": "ohrring",
                "beschreibung": "Boucles pendantes avec fleur en nacre et cascades de perles blanches. Festif et léger.",
                "bild": "uploads/2019/02/P1070662.jpg",
                "vorschau": "uploads/2019/02/P1070662.jpg",
                "material": "Laiton doré, nacre, perles de verre",
                "groesse": "Longueur 5 cm",
                "jahr": "2019",
                "verfuegbarkeit": "Sur demande"
            },
            {
                "id": "marguerite-bar",
                "titel": "Marguerite Bar",
                "kategorie": "ohrring",
                "beschreibung": "Boucles pendantes élégantes : longue barre dorée avec fleur en nacre au bout. Géométrique et féminin.",
                "bild": "uploads/2019/02/P1070663.jpg",
                "vorschau": "uploads/2019/02/P1070663.jpg",
                "material": "Laiton doré, nacre",
                "groesse": "Longueur 6 cm",
                "jahr": "2019",
                "verfuegbarkeit": "Sur demande"
            },
            {
                "id": "pierre-noire",
                "titel": "Pierre Noire",
                "kategorie": "ohrring",
                "beschreibung": "Longue chaîne dorée avec grosses perles en pierre minérale noire. Puissant et moderne.",
                "bild": "uploads/2019/02/P1070672.jpg",
                "vorschau": "uploads/2019/02/P1070672.jpg",
                "material": "Laiton doré, pierre minérale",
                "groesse": "Longueur 8 cm",
                "jahr": "2019",
                "verfuegbarkeit": "Sur demande"
            },
            {
                "id": "atelier-set",
                "titel": "Atelier — Lot de 3",
                "kategorie": "ohrring",
                "beschreibung": "Trois boucles pendantes différentes sur présentoir en bois — Art déco, pierre naturelle, cristal.",
                "bild": "uploads/2019/02/P1070913.jpg",
                "vorschau": "uploads/2019/02/P1070913.jpg",
                "material": "Laiton doré, pierres naturelles",
                "groesse": "Longueur 5–8 cm",
                "jahr": "2019",
                "verfuegbarkeit": "Sur demande"
            },
            {
                "id": "ambre-baltique",
                "titel": "Ambre — Ambre Baltique",
                "kategorie": "ohrring",
                "beschreibung": "Trois paires de boucles pendantes en ambre baltique authentique — du cognac foncé au miel chaud.",
                "bild": "uploads/2019/02/P1070936.jpg",
                "vorschau": "uploads/2019/02/P1070936.jpg",
                "material": "Ambre baltique, laiton doré",
                "groesse": "Longueur 6–8 cm",
                "jahr": "2019",
                "verfuegbarkeit": "Sur demande"
            },
            {
                "id": "grenat",
                "titel": "Grenat",
                "kategorie": "ohrring",
                "beschreibung": "Boucles pendantes avec perles de grenat rouge profond sur fine chaîne dorée. Noble et intemporel.",
                "bild": "uploads/2019/02/P1070934.jpg",
                "vorschau": "uploads/2019/02/P1070934.jpg",
                "material": "Grenat, laiton doré",
                "groesse": "Longueur 7 cm",
                "jahr": "2019",
                "verfuegbarkeit": "Sur demande"
            },
            {
                "id": "creole",
                "titel": "Créole",
                "kategorie": "ohrring",
                "beschreibung": "Grandes créoles ornées de perles Miyuki. Légères comme l'été.",
                "bild": "uploads/2019/02/P1080029.jpg",
                "vorschau": "uploads/2019/02/P1080029.jpg",
                "material": "Laiton doré, perles Miyuki",
                "groesse": "Diamètre 5 cm",
                "jahr": "2019",
                "verfuegbarkeit": "Sur demande"
            },
            {
                "id": "opale-lot-4",
                "titel": "Opale — Lot de 4",
                "kategorie": "armband",
                "beschreibung": "Quatre bracelets délicats avec perles opale bleu clair et fermoir doré. Portables séparément ou ensemble.",
                "bild": "uploads/2019/02/P1070675.jpg",
                "vorschau": "uploads/2019/02/P1070675.jpg",
                "material": "Perles opale, laiton doré",
                "groesse": "Longueur 18 cm",
                "jahr": "2019",
                "verfuegbarkeit": "Sur demande"
            },
            {
                "id": "opale-presentoir",
                "titel": "Opale — Présentoir",
                "kategorie": "armband",
                "beschreibung": "Bracelets opale présentés sur support sombre de l'atelier — esprit maritime.",
                "bild": "uploads/2019/02/P1070683.jpg",
                "vorschau": "uploads/2019/02/P1070683.jpg",
                "material": "Perles opale, laiton doré",
                "groesse": "Longueur 18 cm",
                "jahr": "2019",
                "verfuegbarkeit": "Sur demande"
            },
            {
                "id": "terre-cuite",
                "titel": "Terre Cuite — Ensemble",
                "kategorie": "armband",
                "beschreibung": "Bracelet et boucles d'oreilles en perles de verre couleur terre cuite avec fermoir T-bar doré.",
                "bild": "uploads/2019/02/P1070685.jpg",
                "vorschau": "uploads/2019/02/P1070685.jpg",
                "material": "Perles de verre, laiton doré",
                "groesse": "Bracelet 18 cm",
                "jahr": "2019",
                "verfuegbarkeit": "Sur demande"
            },
            {
                "id": "arch-p1070660",
                "titel": "P1070660",
                "kategorie": "archive",
                "beschreibung": "Bijou de l'atelier Oriabel.",
                "bild": "uploads/2019/02/P1070660.jpg",
                "vorschau": "uploads/2019/02/P1070660.jpg",
                "material": "",
                "groesse": "",
                "verfuegbarkeit": "Sur demande"
            }
        ]
    },
    {
        "id": "kintsugi",
        "section": "oriabel",
        "titre": "Kintsugi",
        "sous_titre": "L'art japonais de réparer avec de l'or — transformer les blessures en beauté.",
        "titre_nav": "Kintsugi",
        "kuenstlerin": "Oriabel",
        "bildform": "square",
        "feld1_key": "material",
        "feld1_label": "Matière",
        "feld2_key": "format",
        "feld2_label": "Format",
        "feld3_key": "",
        "feld3_label": "",
        "kategorien": [],
        "produkte": []
    },
    {
        "id": "peintures",
        "section": "oriabel",
        "titre": "Peintures",
        "sous_titre": "Œuvres peintes par Oriabel.",
        "titre_nav": "Peintures",
        "kuenstlerin": "Oriabel",
        "bildform": "portrait",
        "feld1_key": "technik",
        "feld1_label": "Technique",
        "feld2_key": "format",
        "feld2_label": "Format",
        "feld3_key": "jahr",
        "feld3_label": "Année",
        "kategorien": [],
        "produkte": []
    },
    {
        "id": "travaux",
        "section": "oriabel",
        "titre": "Travaux d'aiguilles",
        "sous_titre": "Broderie, canevas, tapisserie — l'art textile de l'atelier.",
        "titre_nav": "Travaux d'aiguilles",
        "kuenstlerin": "Oriabel",
        "bildform": "square",
        "feld1_key": "material",
        "feld1_label": "Matière",
        "feld2_key": "format",
        "feld2_label": "Format",
        "feld3_key": "",
        "feld3_label": "",
        "kategorien": [],
        "produkte": []
    }
];
